### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by zachgrayio** [csharpseattle/tensorflowiOS#1]
Hey there,

I've been looking for a working example of TF mobile on iOS with the MobileNet SSD model on and off for a few months, but so far all of the examples are out of date.

I'm having trouble getting this running, due to a mismatch of TF version I'm guessing. Any chance you could tell me which version of TF you used when creating this project?

**Comment by csharpseattle** [comment]
Hi Zach,
I hope you figured it out.  I've been having trouble with TF master lately.  The **v1.5.0-rc0** tag works for me.  I've also used **v1.4.1** but note that the Makefile at `tensorflow/contrib/makefile` doesn't support setting ANDROID_TYPES in your environment.  If you checkout the v1.4.1 version you will have to do a search/replace and change "ANDROID_TYPES_SLIM" to "ANDROID_TYPES_FULL" in that file before running build_all_ios.sh.

**Comment by zachgrayio** [comment]
Thanks for the quick reply! 

Yeah, I got it up and running, great example repo. 

We've also been struggling with `master` and out of sync docs. Thanks for the tip on the makefile, will definitely make sure I double check my env vars in the future when troubleshooting builds.
