### ISSUE TITLE
Failed to load model

### ISSUE THREAD

**Issue by yaoliangjun** [csharpseattle/tensorflowiOS#12]
Hi
I try to run on my 6s plus, and the console message is: "Failed to load model"
here is my debug screenshot, any suggestion?

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/7575968/49984040-27f53900-ffa1-11e8-91a2-3a2dba34357a.png">

**Comment by csharpseattle** [comment]
Hi Jerry, 
which model are you trying to load?

**Comment by yaoliangjun** [comment]
this model: "frozen_inference_graph"

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/7575968/49986084-68f14b80-ffa9-11e8-8e33-5d5d9caac58f.png">

**Comment by csharpseattle** [comment]
I'm not sure.  I haven't made changes to those graphs in several months.  It looks like you might have some source control modifications judging by the '?'.    Did you re-train?

**Comment by yaoliangjun** [comment]
thank you anyway, I will try again.

**Comment by ghost** [comment]
I am having the same issue. Could you solve it?

**Comment by yaoliangjun** [comment]
> I am having the same issue. Could you solve it?

We need to build the tensorflow components with ANDROID_TYPES_FULL. In the terminal type:
export ANDROID_TYPES="-D__ANDROID_TYPES_FULL__"
