### ISSUE TITLE
"protoc not found in Tensorflow repo at tensorflow/contrib/makefile/gen/protobuf-host/bin.  Did you set TENSORFLOW_ROOT in tensorflow.xcconfig?"

### ISSUE THREAD

**Issue by takasurazeem** [csharpseattle/tensorflowiOS#4]
The files, string_int_label_map.pb.cc and string_int_label_map.pb.h  are missing, where can I find those corresponding files?

**Comment by yuzhou164** [comment]
@takasurazeem I faced the same problem. Could you mind sharing your solution?

**Comment by japer21** [comment]
@yuzhou164 You need also to set the root repository of your tensorflow in tensorflow.xcconfig otherwise it won't build. So you set the TENSORFLOW_ROOT in the Build Settings of the xcode project and also you set the TENSORFLOW_ROOT variable in the file SupportingFiles/tensorflow.xcconfig

**Comment by japer21** [comment]
@yuzhou164 
![image](https://user-images.githubusercontent.com/17979719/43259064-4d472f50-90d5-11e8-8fc5-a4ebfad20e99.png)
![image](https://user-images.githubusercontent.com/17979719/43259118-7561fd12-90d5-11e8-86f2-e6e002c26dac.png)
