### ISSUE TITLE
/tensorflowiOS/swift/Tensorflow/: No such file or directory

### ISSUE THREAD

**Issue by takasurazeem** [csharpseattle/tensorflowiOS#5]
I have added the screenshot for the better demonstration of the error.
![image](https://user-images.githubusercontent.com/2876680/36979109-4c5ff556-20a8-11e8-8781-6a6d650134fb.png)
Can not generate the string_int_label_map file

**Comment by xiangcong** [comment]
same problem

**Comment by xiangcong** [comment]
solved.  just run BuildPhase.sh first
